language: python
dist: focal
sudo: true
python: 3.6
branches: master

before_install:
  - sudo apt-get install -y build-essential fpc lcl lazarus
  
install:
  - pip install mkdocs  

script: make clean all

before_deploy:
  - mkdocs build --verbose --clean --strict
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: site
  on:
    branch: master  
